package com.frank.reservations;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*********************************************************************
 * This is an example of a Spring Boot 2 server
 * 
 * Spring is collection of open source frameworks
 * 
 * Spring Boot 2 is one of the Spring frameworks for REST API Servers
 * 
 * This code was generated by Spring Boot Initializr
 * 
 * Spring Boot Initializr will generate the base code for a Spring Boot app
 * 
 * You RARELY need to change anything in this code
 * (DON"T change anything in this code unless you know what you're doing)
 **********************************************************************/

// This tells the server this is a Spring Boot application 
 @SpringBootApplication
public class HotelReservationsApplication {

    // This is the start of the application - main()
    public static void main(String[] args) {
        // Tell Spring Boot to start a server for the application
        //      using any arguments passed to the main (args)
        SpringApplication.run(HotelReservationsApplication.class, args);
    }

}
